### PR TITLE
code for classic snake game

### PR DESCRIPTION
**Pull request by codewarsfx**
pr containes code for snake game made with js canvas

### CODE REVIEW

**Comment by Anamaya1729** [comment]
Please upload/include the necessary files to make the project work.

**Comment by codewarsfx** [comment]
> Please upload/include the necessary files to make the project work.

hi @Anamaya1729 all the necessary files have been uploaded i.e index.html and snake.js..doesnt it work on your end?

**Comment by Anamaya1729** [comment]
Are you using p5js? If yes, you did not included it into index.html file.

**Comment by codewarsfx** [comment]
> Are you using p5js? If yes, you did not included it into index.html file.

im not using that...I built this with canvas html5 api..no extra dependency

**Review by Anamaya1729 — APPROVED** [review]

**Comment by Anamaya1729** [comment]
Thanks for the contribution! Please support the repo by giving it a star!

**Pull request merged**
