### PR TITLE
added guess-my-number game

### PR DESCRIPTION
**Pull request by Khushi-dev-1822**
I have made a simple game using javaScript i.e. Guess my number.

### CODE REVIEW

**Comment by Anamaya1729** [comment]
Please create a pull request for the projects that are available if you want to add a project than create issue for it.

**Review by Anamaya1729 — APPROVED** [review]

**Comment by Anamaya1729** [comment]
Thanks for the contribution. Please support the repository by giving it a star.

**Review by Anamaya1729 — COMMENTED** [review]
hacktoberfest-accepted

**Comment by Khushi-dev-1822** [comment]
Will this count in hacktoberfest?

**Comment by Anamaya1729** [comment]
Please create a pull request in the project folder.

**Comment by Anamaya1729** [comment]
yes!

**Pull request merged**
