### PR TITLE
add password generator to easy projects;

### PR DESCRIPTION
**Pull request by ATH42**

### CODE REVIEW

**Comment by ATH42** [comment]
i just saw, that you already added a picture, do you want me too restyle mine?

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Please add the README.md in which describe the project, add some image example of project.

**Review by Anamaya1729 — APPROVED** [review]
hacktoberfest-accepted

**Comment by ATH42** [comment]
thanks for your review, happy hacking to you guys :)

**Comment by Anamaya1729** [comment]
Thanks for your contribution. Please star the repository to support it.

**Pull request merged**
