### PR TITLE
create(card-memory-game): easy level JavaScript project added

### PR DESCRIPTION
**Pull request by monieshravichandrran**
Card Memory game Application using JS 

Level - Easy

### CODE REVIEW

**Review by Anamaya1729 — COMMENTED** [review]
This project looks really well done. You can move this project to `medium/ ` directory. Add the README.md file with description and sample images in it. Commit these changes to complete the contribution.

**Comment by monieshravichandrran** [comment]
> This project looks really well done. You can move this project to `medium/ ` directory. Add the README.md file with description and sample images in it. Commit these changes to complete the contribution.

Done moved it to medium @Anamaya1729

**Comment by Anamaya1729** [comment]
Add README.md for it.

**Review by Anamaya1729 — APPROVED** [review]

**Comment by monieshravichandrran** [comment]
@Anamaya1729 added a descriptive README

**Comment by Anamaya1729** [comment]
Thanks for the contribution. Please star the repository to support the project.

**Comment by monieshravichandrran** [comment]
> Thanks for the contribution. Please star the repository to support the project.

Sure Thank you.

**Pull request merged**
