### PR TITLE
text editor added under hacktoberfest 2022

### PR DESCRIPTION
**Pull request by abhijain2003**
Hey I have added text editor in this repo, please merge it under hacktoberfest 2022

### CODE REVIEW

**Comment by Anamaya1729** [comment]
Add it in `easy/` directory.

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Add a README.md file.

**Comment by abhijain2003** [comment]
Done sir

**Review by Anamaya1729 — COMMENTED** [review]
Okay, just a readme.md file left.

**Comment by abhijain2003** [comment]
everything is done now please merge it

**Review by vaibhava17 — APPROVED** [review]

**Comment by vaibhava17** [comment]
Thank You for your contribution and please star this repo

**Comment by abhijain2003** [comment]
why it is showing not accepted on hacktoberfest website

can anyone help me in this

**Pull request merged**
