### PR TITLE
Color-Palette With Corresponding Hex Values

### PR DESCRIPTION
**Pull request by GeekkyCoder**

### CODE REVIEW

**Comment by GeekkyCoder** [comment]
Okay Anamaya, i will add the readme.md file but  i have pulled this request
for medium dir, do you want me to move it to easy dir?

**Comment by Anamaya1729** [comment]
Yes, please!

**Comment by GeekkyCoder** [comment]
Okay!

**Comment by GeekkyCoder** [comment]
Can you merge my request now,  have made a new PR request as per say!

**Comment by GeekkyCoder** [comment]
Can you merge my request now,  have made a new PR request as per say!

**Comment by Anamaya1729** [comment]
Please refer to #45

**Pull request closed without merging**
