### PR TITLE
Tic Tac Toe Game

### PR DESCRIPTION
**Pull request by rakshitdabral**
Basic design and working project
Screenshot (6)

### CODE REVIEW

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Your `README.md` file is in another directory. Please correct it.

**Comment by rakshitdabral** [comment]
> Your `README.md` file is in another directory. Please correct it.

I think its in same directory 
Screenshot (7)

**Comment by Anamaya1729** [comment]
Please check the PR and files you are changing.

**Comment by rakshitdabral** [comment]
> Please check the PR and files you are changing.

ok my files are good the thing that i am not changing is that feedback form.  But that the thing you have to merge in the master or i  will have to delete it in my PR

**Comment by rakshitdabral** [comment]
You can check now i think its working now

**Review by Anamaya1729 — COMMENTED** [review]
You Added the `README.md` in Sounds and feedback_page dir is still not cleared. Please correct it.

**Comment by rakshitdabral** [comment]
> You Added the `README.md` in Sounds and feedback_page dir is still not cleared. Please correct it.

Please check your master branch i think there  is unmerged README.md file in feedback directory as i am not modifying it

**Comment by Anamaya1729** [comment]
You edited your README.md file in feedback_file created a commit there. Then you moved it to tic tac toe folder, but the original commit was created to modify the readme in feedback_file. Please correct this issue.

**Pull request closed without merging**
