### PR TITLE
add modal example; copy and pastable example;

### LINKED ISSUE #16: Modal Example
I'd love to add an example on how to use Pop up Modals in vanilla javascript

### PR DESCRIPTION
**Pull request by ATH42**
closes #16

### CODE REVIEW

**Comment by ATH42** [comment]
hey Peeps, i added a simple and customizable example on modal functionality.

**Comment by Anamaya1729** [comment]
Please create an issue if you want to add a project with project description.

**Comment by ATH42** [comment]
closes #16

**Comment by ATH42** [comment]
> Please create an issue if you want to add a project with project description.

created issue #16
is its ok like that?

**Pull request closed without merging**
